from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator


class Telemetry(models.Model):
    """Telemetry point from PrintSat."""
    station = models.CharField(max_length=20)
    lat = models.DecimalField(max_digits=10, decimal_places=5)
    lon = models.DecimalField(max_digits=10, decimal_places=5)
    program = models.CharField(max_length=30)
    telem_type = models.CharField(max_length=20)
    ps_time = models.DateTimeField()
    ps_time_calc = models.DateTimeField()
    bat_v = models.DecimalField(max_digits=6, decimal_places=2)
    bat_i = models.DecimalField(max_digits=6, decimal_places=2)
    sp1_v = models.DecimalField(max_digits=6, decimal_places=2)
    sp1_i = models.DecimalField(max_digits=6, decimal_places=2)
    sp2_v = models.DecimalField(max_digits=6, decimal_places=2)
    sp2_i = models.DecimalField(max_digits=6, decimal_places=2)
    exp_1 = models.DecimalField(max_digits=5, decimal_places=2)
    sp3_v_five = models.DecimalField(max_digits=5, decimal_places=2)
    sp3_i_five = models.DecimalField(max_digits=5, decimal_places=2)
    exp_0 = models.DecimalField(max_digits=5, decimal_places=2)
    sp4_v_eight = models.DecimalField(max_digits=5, decimal_places=2)
    sp4_i_eight = models.DecimalField(max_digits=5, decimal_places=2)
    five_v = models.DecimalField(max_digits=5, decimal_places=2)
    five_i = models.DecimalField(max_digits=6, decimal_places=2)
    three_v = models.DecimalField(max_digits=5, decimal_places=2)
    three_i = models.DecimalField(max_digits=5, decimal_places=2)
    load_cell = models.DecimalField(max_digits=6, decimal_places=2)
    sp1_temp = models.DecimalField(max_digits=5, decimal_places=2)
    sp3_temp = models.DecimalField(max_digits=5, decimal_places=2)
    bat_temp = models.DecimalField(max_digits=5, decimal_places=2)
    five_vreg_temp = models.DecimalField(max_digits=5, decimal_places=2)
    wilt_cell_temp = models.DecimalField(max_digits=5, decimal_places=2)
    wilt_cell_i = models.DecimalField(max_digits=5, decimal_places=2)
    wilt_cell_v = models.DecimalField(max_digits=5, decimal_places=2)
    decode_dflt_errs = models.DecimalField(max_digits=6, decimal_places=2)
    readrad_timeout_errs = models.DecimalField(max_digits=6, decimal_places=2)
    tlm_intervl = models.DecimalField(max_digits=6, decimal_places=2)
    software_2 = models.DecimalField(max_digits=6, decimal_places=2)
    software_3 = models.DecimalField(max_digits=6, decimal_places=2)
    software_4 = models.DecimalField(max_digits=6, decimal_places=2)
    software_5 = models.DecimalField(max_digits=6, decimal_places=2)
    portc = models.DecimalField(max_digits=6, decimal_places=2)
    rad_cmd_count = models.DecimalField(max_digits=6, decimal_places=2)
    rad_temp = models.DecimalField(max_digits=6, decimal_places=2)
    rad_rssi = models.DecimalField(max_digits=5, decimal_places=2)
    udoslo = models.DecimalField(max_digits=5, decimal_places=2)
    msu_i_1 = models.DecimalField(max_digits=5, decimal_places=2)
    udos_med = models.DecimalField(max_digits=5, decimal_places=2)
    msu_temp_1 = models.DecimalField(max_digits=5, decimal_places=2)
    udos_hi = models.DecimalField(max_digits=5, decimal_places=2)
    msu_i_2 = models.DecimalField(max_digits=5, decimal_places=2)
    udos_log = models.DecimalField(max_digits=5, decimal_places=2)
    msu_temp_2 = models.DecimalField(max_digits=5, decimal_places=2)
    mus_i_3 = models.DecimalField(max_digits=5, decimal_places=2)
    msu_temp_4 = models.DecimalField(max_digits=5, decimal_places=2)
    msu_temp_3 = models.DecimalField(max_digits=5, decimal_places=2)
    testv1 = models.DecimalField(max_digits=5, decimal_places=2)
    testi1 = models.DecimalField(max_digits=5, decimal_places=2)
    testv2 = models.DecimalField(max_digits=5, decimal_places=2)
    testi2 = models.DecimalField(max_digits=5, decimal_places=2)
    testv3 = models.DecimalField(max_digits=5, decimal_places=2)
    testi3 = models.DecimalField(max_digits=5, decimal_places=2)
    testv4 = models.DecimalField(max_digits=5, decimal_places=2)
    testi4 = models.DecimalField(max_digits=5, decimal_places=2)
    testv5 = models.DecimalField(max_digits=5, decimal_places=2)
    testi5 = models.DecimalField(max_digits=5, decimal_places=2)
    testv6 = models.DecimalField(max_digits=5, decimal_places=2)
    testi6 = models.DecimalField(max_digits=5, decimal_places=2)
    testv7 = models.DecimalField(max_digits=5, decimal_places=2)
    testi7 = models.DecimalField(max_digits=5, decimal_places=2)
    testv8 = models.DecimalField(max_digits=5, decimal_places=2)
    testi8 = models.DecimalField(max_digits=5, decimal_places=2)
    testv9 = models.DecimalField(max_digits=5, decimal_places=2)
    testi9 = models.DecimalField(max_digits=5, decimal_places=2)
    testv10 = models.DecimalField(max_digits=5, decimal_places=2)
    testi10 = models.DecimalField(max_digits=5, decimal_places=2)
    testv11 = models.DecimalField(max_digits=5, decimal_places=2)
    testi11 = models.DecimalField(max_digits=5, decimal_places=2)
    testv12 = models.DecimalField(max_digits=5, decimal_places=2)
    testi12 = models.DecimalField(max_digits=5, decimal_places=2)
    testv13 = models.DecimalField(max_digits=5, decimal_places=2)
    testi13 = models.DecimalField(max_digits=5, decimal_places=2)
    testv14 = models.DecimalField(max_digits=5, decimal_places=2)
    testi14 = models.DecimalField(max_digits=5, decimal_places=2)
    testv15 = models.DecimalField(max_digits=5, decimal_places=2)
    testi15 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv1 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni1 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv2 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni2 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv3 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni3 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv4 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni4 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv5 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni5 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv6 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni6 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv7 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni7 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv8 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni8 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv9 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni9 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv10 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni10 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv11 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni11 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv12 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni12 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv13 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni13 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv14 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni14 = models.DecimalField(max_digits=5, decimal_places=2)
    knownv15 = models.DecimalField(max_digits=5, decimal_places=2)
    knowni15 = models.DecimalField(max_digits=5, decimal_places=2)
    imm_temp = models.DecimalField(max_digits=5, decimal_places=2)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta(object):
        ordering = ['ps_time']
        verbose_name_plural = "telemetry"

    def __unicode__(self):
        return self.ps_time


class Upload(models.Model):
    """Track Uploaded Files"""
    file = models.FileField(upload_to=settings.MEDIA_ROOT)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)